// src/components/Card.tsx
import { Category } from '../models/Category'
import { Link } from '../models/Link'

export const Card = ({ name, links } : Category) => {
    return (
        <div className="card">
            <div className="card-header">
                <span>{ name }</span>
            </div>
            <div className="card-body">
                <ul>
                    { 
                        links.map((item: Link, i: number) => 
                            <a key={ i } href={ item.url }><li>{ item.name }</li></a>
                        )
                    }
                </ul>
            </div>
        </div>
    )
}

// src/components/Card.vue
<template>
    <div class="card">
        <div class="card-header">
            <span>{{ title }}</span>
        </div>
        <div class="card-body">
            <ul>
                <li v-for="item in items" :key="item.link"><a :href="item.link">{{ item.name }}</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
export default {
  name: 'Card',
  props: {
    title: String,
    items: Array,
  }
}
</script>
