// src/App.tsx
import './App.css'

function App() {
    const categories: Category[] = [
        {
            name: "Fun", 
            links: [
                {name: "/r/programming", url: "https://reddit.com/r/programming"},
                {name: "YouTube", url: "https://youtube.com"},
                {name: "Netflix", url: "https://netflix.com"}
            ]
        },
        {
            name :"Code", 
            links: [
                {name: "GitHub", url: "https://github.com"}, 
                {name: "GitLab", url: "https://gitlab.com"}
            ]
        }
    ]
  return (
    <div className="App">
        <div className="holder"> 
            {categories.map(category => <Card category={category} />)}
        </div>
    </div>
  )
}

const Card = ({ category }: Category) => {
    return (
        <div className="card">
            <div className="card-header">
                <span>{ category.name }</span>
            </div>
            <div className="card-body">
                <ul>
                    { category.links.map((item: Link) => <a href={ item.url }><li>{ item.name }</li></a>)}
                </ul>
            </div>
        </div>
    )
}

interface Category {
    name: string;
    links: Link[];
}

interface Link {
    name: string;
    url: string;
}
export default App

// src/App.vue
<template>
    <div class="holder">
        <div class="card">
            <div class="card-header">
                <span>Fun</span>
            </div>
            <div class="card-body">
                <ul>
                    <li><a href="https://reddit.com/r/programming">/r/programming</a></li>
                    <li><a href="https://youtube.com">YouTube</a></li>
                    <li><a href="https://netflix.com">Netflix</a></li>
                </ul>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <span>Code</span>
            </div>
            <div class="card-body">
                <ul>
                    <li><a href="https://github.com">GitHub</a></li>
                    <li><a href="https://gitlab.com">GitLab</a></li>
                </ul>
            </div>
        </div>
    </div>
</template>

<script>
export default {
  name: 'App',
}
</script>

<style>
.holder {
    display: flex;
    flex-direction: row;
    justify-content: center;
}

.card-body {
    margin: 5px 5px 0px 5px;
}

.card {
    display: inline;
    margin: 10px;
}

.card-header {
    border-bottom: #11e6be solid 1px;
    padding-bottom: 2px;
}
body {
    background-color: #121212;
}
a {
    color: #f1f1f1;
    text-decoration: none;
}
a:hover {
    color: #121212;
}

li:hover {
    color: #121212;
    background-color: #11e6be;
    text-decoration: none;
}
ul {
    padding:0;
    margin:0;
    text-align: left;
    list-style-type: none;
}

#app {
  font-family: Roboto Mono, monospace;
  text-align: center;
  color: #f1f1f1;
  margin-top: 60px;
}
</style>
